"""add_indexes_phase2

Revision ID: 08cb42921977
Revises: 
Create Date: 2026-04-15 17:19:47.267895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '08cb42921977'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_clubs_admin_id'), 'clubs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_events_attendance_qr_code'), 'events', ['attendance_qr_code'], unique=False)
    op.create_index(op.f('ix_events_club_id'), 'events', ['club_id'], unique=False)
    op.create_index(op.f('ix_events_start_time'), 'events', ['start_time'], unique=False)
    op.create_index(op.f('ix_follows_club_id'), 'follows', ['club_id'], unique=False)
    op.create_index(op.f('ix_follows_user_id'), 'follows', ['user_id'], unique=False)
    op.create_index(op.f('ix_rsvps_created_at'), 'rsvps', ['created_at'], unique=False)
    op.create_index(op.f('ix_rsvps_event_id'), 'rsvps', ['event_id'], unique=False)
    op.create_index(op.f('ix_rsvps_user_id'), 'rsvps', ['user_id'], unique=False)
    # NOTE: op.drop_column for stale 'users' columns omitted — those columns
    # were already removed from the live database in a prior untracked migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rsvps_user_id'), table_name='rsvps')
    op.drop_index(op.f('ix_rsvps_event_id'), table_name='rsvps')
    op.drop_index(op.f('ix_rsvps_created_at'), table_name='rsvps')
    op.drop_index(op.f('ix_follows_user_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_club_id'), table_name='follows')
    op.drop_index(op.f('ix_events_start_time'), table_name='events')
    op.drop_index(op.f('ix_events_club_id'), table_name='events')
    op.drop_index(op.f('ix_events_attendance_qr_code'), table_name='events')
    op.drop_index(op.f('ix_clubs_admin_id'), table_name='clubs')
    # ### end Alembic commands ###
